### ISSUE TITLE
loki upgrade fails: Deployment "loki-loki-distributed-gateway" exceeded its progress deadline

### ISSUE THREAD

**Issue by bastiaanb** [kuberise/kuberise.io#133]
On a single node on-prem cluster, Loki upgrade fails: the new loki-loki-distributed-gateway pod cannot be scheduled because anti-affinity rules prevent deployment on the same node as the old pod:
```
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app.kubernetes.io/component: gateway
                  app.kubernetes.io/instance: loki
                  app.kubernetes.io/name: loki-distributed
              topologyKey: failure-domain.beta.kubernetes.io/zone
            weight: 100
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                app.kubernetes.io/component: gateway
                app.kubernetes.io/instance: loki
                app.kubernetes.io/name: loki-distributed
            topologyKey: kubernetes.io/hostname
```
