### ISSUE TITLE
KeyCloak not working

### ISSUE THREAD

**Issue by appie2go** [kuberise/kuberise.io#63]
Hi Mojtaba,

I just installed my cluster and I'm running into the issue that my KeyCloak instance is not working. It says: 'CrashLoopBackOff'. What's the problem? Where can I find the logs anyways?

This is my config:

```yaml
applications:

  hello:
    enabled: true
    path: values/local-example/applications/dev/hello

  cnpg-database:
    enabled: false
    path: values/local-example/platform/database/

  raw:
    enabled: false
    path: values/local-example/platform/raw

helmCharts:
  keycloak:
    enabled: true

  keycloak-operator:
    enabled: true

  ingress-nginx:
    enabled: false

  kube-prometheus-stack:
    enabled: false

  loki:
    enabled: false

  promtail:
    enabled: false

  cloudnative-pg:
    enabled: false

  pgadmin:
    enabled: false

  cert-manager:
    enabled: false

  backstage:
    enabled: false

  sealed-secrets:
    enabled: false

  ingresses:
    enabled: false

  # Microservice helm charts for the dev environment

  todolist-frontend-dev:
    enabled: false
    values: defaults/applications/dev/todolist/frontend/values.yaml

  todolist-backend-dev:
    enabled: false
    values: defaults/applications/dev/todolist/backend/values.yaml

  show-env-dev:
    enabled: false
    values: defaults/applications/dev/show-env/values.yaml

# Microservice helm charts for the tst environment

  todolist-frontend-tst:
    enabled: false
    values: defaults/applications/tst/todolist/frontend/values.yaml


# Microservice helm charts for the prd environment

  todolist-frontend-prd:
    enabled: false
    values: defaults/applications/prd/todolist/frontend/values.yaml
```
